#!/bin/sh

VERSION=$1

function install_package {
  local app=$1
  echo Installing py$VERSION-$app
  sudo port -q install py$VERSION-$app
  sudo port -q select --set $app $app$VERSION 
}

if [[ $(uname) = Darwin ]]; then
  echo "Switching via MacPorts to Python $VERSION"
  sudo port -q install python$VERSION
  sudo port -q select --set python python$VERSION
  install_package ipython
  install_package pip
fi
